# Generated by Django 5.2.15 on 2026-06-17 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('renda_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aporte_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva_de_emergencia', models.BooleanField(default=False)),
                ('valor_armazenado_reserva_emergencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('possui_dividas', models.BooleanField(default=True)),
                ('objetivo_de_vida', models.CharField(choices=[('Aposentar', 'Aposentar'), ('Imovel', 'Imovel'), ('Viagens', 'Viagens'), ('Renda_passiva', 'Renda_passiva')])),
                ('tempo_estimado_retorno', models.IntegerField()),
                ('valor_desejado_acumulado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preocupacao_atual', models.CharField(max_length=500)),
            ],
        ),
    ]
