# Generated by Django 5.2.15 on 2026-06-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='aporte_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='objetivo_de_vida',
            field=models.CharField(choices=[('Aposentar', 'Aposentar'), ('Imovel', 'Imovel'), ('Viagens', 'Viagens'), ('Renda_passiva', 'Renda Passiva')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='renda_atual',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='valor_armazenado_reserva_emergencia',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='valor_desejado_acumulado',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
