# Generated by Django 5.2.15 on 2026-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_aporte_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tipo_de_investidor',
            field=models.CharField(choices=[('Conservador', 'Conservador'), ('Moderado', 'Moderado'), ('Agressivo', 'Agressivo')], default='Moderado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='objetivo_de_vida',
            field=models.CharField(choices=[('Aposentadoria', 'Aposentadoria'), ('Imovel', 'Imovel'), ('Viagens', 'Viagens'), ('Renda_passiva', 'Renda Passiva')]),
        ),
    ]
