# Generated by Django 5.2.15 on 2026-06-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_tipo_de_investidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tipo_de_investidor',
            field=models.CharField(blank=True, choices=[('Conservador', 'Conservador'), ('Moderado', 'Moderado'), ('Agressivo', 'Agressivo')], null=True),
        ),
    ]
