# Generated by Django 5.2.15 on 2026-06-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_tipo_de_investidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='perfil_sintetico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
