# Generated by Django 5.2.15 on 2026-06-21 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_perfil_sintetico'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='aceitacao_perda_percentual',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='client',
            name='experiencia_em_investimentos',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediario'), ('Avancado', 'Avancado')], default='Iniciante'),
        ),
        migrations.AddField(
            model_name='client',
            name='liquidez_necessaria',
            field=models.CharField(choices=[('Imediata', 'Imediata'), ('Curto_prazo', 'Curto prazo'), ('Medio_prazo', 'Medio prazo'), ('Longo_prazo', 'Longo prazo')], default='Imediata'),
        ),
        migrations.AddField(
            model_name='client',
            name='tolerancia_volatilidade',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='objetivo_de_vida',
            field=models.CharField(choices=[('Aposentadoria', 'Aposentadoria'), ('Imovel', 'Imovel'), ('Viagens', 'Viagens'), ('Preservacao', 'Preservacao'), ('Renda_passiva', 'Renda Passiva')]),
        ),
    ]
