# Generated by Django 5.2.15 on 2026-06-25 01:06

import core.guardrails.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_aceitacao_perda_percentual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='aceitacao_perda_percentual',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='aporte_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, validators=[core.guardrails.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='client',
            name='experiencia_em_investimentos',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Iniciante', 'Iniciante'), ('Intermediario', 'Intermediario'), ('Avancado', 'Avancado')], default='Iniciante', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='liquidez_necessaria',
            field=models.CharField(choices=[('Imediata', 'Imediata'), ('Curto_prazo', 'Curto prazo'), ('Medio_prazo', 'Medio prazo'), ('Longo_prazo', 'Longo prazo')], default='Imediata', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='nome',
            field=models.CharField(max_length=150, validators=[core.guardrails.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='client',
            name='objetivo_de_vida',
            field=models.CharField(choices=[('Aposentadoria', 'Aposentadoria'), ('Imovel', 'Imovel'), ('Viagens', 'Viagens'), ('Preservacao', 'Preservacao'), ('Renda_passiva', 'Renda Passiva')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='preocupacao_atual',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='renda_atual',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='tempo_estimado_retorno',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='tipo_de_investidor',
            field=models.CharField(blank=True, choices=[('Conservador', 'Conservador'), ('Moderado', 'Moderado'), ('Agressivo', 'Agressivo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='valor_armazenado_reserva_emergencia',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='valor_desejado_acumulado',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
