# Generated by Django 5.2.15 on 2026-06-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_aceitacao_perda_percentual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='objetivo_de_vida',
            field=models.CharField(choices=[('Aposentadoria', 'Aposentadoria'), ('Imovel', 'Imovel'), ('Viagens', 'Viagens'), ('Renda_passiva', 'Renda Passiva'), ('Educacao', 'educacao'), ('Protecao_patrimonial', 'Protecao_Patrimonial'), ('Empreender', 'Empreender'), ('Independencia_financeira', 'Independencia Financeira')], max_length=30),
        ),
    ]
