# Generated by Django 5.2.15 on 2026-06-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('risco', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilInvestidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('rentabilidade_anual', models.DecimalField(decimal_places=2, help_text='Percentual médio anual', max_digits=6)),
                ('volatilidade', models.DecimalField(decimal_places=2, help_text='Percentual', max_digits=6)),
                ('liquidez_dias', models.IntegerField()),
                ('risco', models.IntegerField(help_text='1 a 5')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo_investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.classeativo')),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField()),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.investimento')),
            ],
        ),
        migrations.AddField(
            model_name='classeativo',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='investimentos.perfilinvestidor'),
        ),
    ]
